### ISSUE TITLE
sorry for issue.

### ISSUE THREAD

**Issue by blackcoder0x01** [gennaro-tedesco/gh-f#14]
I want to add this spin on my little script but I don't know how to add it. please could you show me the code. Please

![image](https://user-images.githubusercontent.com/66354644/158342138-69028570-851a-44ae-a1c4-7dd987315b8d.png)

**Comment by gennaro-tedesco** [comment]
Good morning! The spinner widget that you see on the left hand side is not a property of this extension, rather of the shell and the pager you are using to render markdown files in your terminal. `gh` CLI uses [glow](https://github.com/charmbracelet/glow) as per [here](https://github.com/cli/cli/issues/2007) and if I remember correctly that should be sufficient; you may need to also explicitly tell `gh` to use a different pager, I personally use [delta](https://github.com/dandavison/delta) and you can configure it via `gh config set pager 'delta -s'`.

My full terminal configuration with `zsh` is [here](https://github.com/gennaro-tedesco/dotfiles/tree/master/zsh) and the corresponding `git` configurations (pagers, renders and the like) can be found [here](https://github.com/gennaro-tedesco/dotfiles/tree/master/git) (in case you want to double check what settings I have on).

I will close the issue as it is unrelated to the project (but feel free to comment on if you need further help, however again I presume this is delegated to the prompt and shell you are using).
