### ISSUE TITLE
[Feature] Add command to show where source file is

### ISSUE THREAD

**Issue by davidgoldcode** [gennaro-tedesco/gh-f#24]
Love the tool, thank you for building it! I want to edit the colors directly on the source code, but I can't figure out where to find the source code 🤷‍♂️

**Comment by gennaro-tedesco** [comment]
You can find colours definition [here](https://github.com/gennaro-tedesco/gh-f/blob/master/gh-f#L6-L9) (I believe those lines are linked in the README too).

Let me know if you succeed to change them!
